#!/bin/sh
# File generated by ocamlbuild

cd /home/lucas/ENS/Info/SysDig/minijazz/src/_build

rm -f myocamlbuild.cmi
rm -f myocamlbuild.cmx
rm -f myocamlbuild.o
rm -f myocamlbuild_config.cmi
rm -f myocamlbuild_config.cmx
rm -f myocamlbuild_config.o
# Also clean the script itself
rm -f /home/lucas/ENS/Info/SysDig/minijazz/src/_build/_build/sanitize.sh
